find g++ binaries

diff --git a/template/limits/c.erb b/template/limits/c.erb
--- a/template/limits/c.erb
+++ b/template/limits/c.erb
@@ -11,6 +11,19 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 CHECKER_PATH="$DIR/../files/<%= checker_path %>"
 CHECKER_OUT="$DIR/../files/checker"
 
-g++ -std=c++11 $CHECKER_PATH -o $CHECKER_OUT
+# find compiler
+cc=\`which g++\`
+[ -x "\$cc" ] || cc=/usr/bin/g++
+if [ ! -x "\$cc" ]; then
+    echo "\$cc not found or it's not executable"
+    exit 47
+fi
+
+$cc -std=c++11 -static -O2 -lm $CHECKER_PATH -o $CHECKER_OUT
+
+if [ $? -ne 0 ]; then
+  echo "Checker could not be compiled"
+  exit 47
+fi
 
 exit 0
