porra de boca

diff --git a/template/compile/cpp.erb b/template/compile/cpp.erb
--- a/template/compile/cpp.erb
+++ b/template/compile/cpp.erb
@@ -41,6 +41,31 @@
 
 umask 0022
 
+
+# compile checker
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+mkdir $DIR/../files 2> /dev/null
+
+CHECKER_PATH="$DIR/../files/<%= checker_path %>"
+CHECKER_OUT="checker"
+
+# find compiler
+cc=`which g++`
+[ -x "$cc" ] || cc=/usr/bin/g++
+if [ ! -x "$cc" ]; then
+    echo "$cc not found or it's not executable"
+    exit 47
+fi
+
+$cc -std=c++11 -static -O2 -lm $CHECKER_PATH -o $CHECKER_OUT 2> /dev/null
+
+if [ $? -ne 0 ]; then
+  echo "Checker could not be compiled"
+  exit 47
+fi
+
+
+
 if [ "$1" == "" ]; then
     echo "parameter problem"
     exit 43
@@ -170,3 +195,4 @@ if [ "$ret" != "0" ]; then
 	ret=1
 fi
 exit $ret
+
